In [1]:
import torch

In [4]:
x = torch.empty(3, 2, 3)
x

tensor([[[1.1561e+19, 2.7517e+12, 7.5338e+28],
         [1.2988e-08, 6.9983e+28, 1.1560e+19]],

        [[1.2102e+25, 1.1562e+19, 7.3867e+20],
         [2.0027e-19, 1.4587e-19, 1.8888e+31]],

        [[1.6216e-19, 1.4587e-19, 1.1578e+27],
         [2.6059e-12, 7.5555e+31, 4.0939e-14]]])

In [6]:
# Creat tensor with value 0
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Creat tensor with value 1
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Give data type
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)


torch.int32


In [9]:
# Take the size of tensor
x = torch.ones(2, 2, dtype=torch.float64)
print(x.size())

torch.Size([2, 2])


#### **Basic Operation**

In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

# Add
z = x + y
# Or use
z = torch.add(x, y)
print(z)

tensor([[0.0286, 0.9234],
        [0.4234, 0.5385]])
tensor([[0.6370, 0.3038],
        [0.9599, 0.3113]])
tensor([[0.6656, 1.2271],
        [1.3834, 0.8498]])


In [12]:
# Substraction
z = x - y
# or use
z = torch.subtract(x, y)
z

tensor([[-0.6083,  0.6196],
        [-0.5365,  0.2272]])

In [13]:
# Multiplication
z = x * y
z = torch.mul(x, y)
z

tensor([[0.0182, 0.2805],
        [0.4065, 0.1676]])

In [14]:
# division
z = x / y
z = torch.div(x, y)
z

tensor([[0.0450, 3.0395],
        [0.4411, 1.7300]])

#### **Slicing**

In [20]:
x = torch.rand(5, 3)
print(x)
print(x[1, :])
print(x[1, 2].item())

tensor([[0.2355, 0.7162, 0.9708],
        [0.0839, 0.9457, 0.8645],
        [0.2474, 0.2736, 0.9698],
        [0.6192, 0.4027, 0.9247],
        [0.4646, 0.4562, 0.4793]])
tensor([0.0839, 0.9457, 0.8645])
0.8645023703575134


#### **Auto Grad**

In [21]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [22]:
y = torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [23]:
y.backward()

In [24]:
x.grad

tensor(7.3891)